# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates ici-kendall-tau
#' 
#' @param x numeric vector
#' @param y numeric vector
#' @param perspective should we consider the "local" or "global" perspective?
#' 
#' @examples 
#' data("grp_cor_data")
#' exp_data = grp_cor_data$data
#' x = exp_data[, 1]
#' y = exp_data[, 2]
#' kendallt(x, y)
#' cor(x, y, method = "kendall") 
#' 
#' x = sort(rnorm(100))
#' y = x + 1
#' y2 = y
#' y2[1:10] = NA
#' kendallt(x, y)
#' kendallt(x, y2, "global")
#' kendallt(x, y2)
#' 
#' @importFrom Rcpp sourceCpp
#' @export
#' @useDynLib visualizationQualityControl
#' @return kendall tau correlation
ici_kendallt <- function(x, y, perspective = "local", output = "simple") {
    .Call('_visualizationQualityControl_ici_kendallt', PACKAGE = 'visualizationQualityControl', x, y, perspective, output)
}

#' Calculates ici-kendall-tau
#' 
#' @param x numeric vector
#' @param y numeric vector
#' @param perspective should we consider the "local" or "global" perspective?
#' 
#' @examples 
#' data("grp_cor_data")
#' exp_data = grp_cor_data$data
#' x = exp_data[, 1]
#' y = exp_data[, 2]
#' kendallt(x, y)
#' cor(x, y, method = "kendall") 
#' 
#' x = sort(rnorm(100))
#' y = x + 1
#' y2 = y
#' y2[1:10] = NA
#' kendallt(x, y)
#' kendallt(x, y2, "global")
#' kendallt(x, y2)
#' 
#' @importFrom Rcpp sourceCpp
#' @useDynLib visualizationQualityControl
#' @keywords internal
#' @return kendall tau correlation
ici_ref_kendallt <- function(x, y, perspective = "local", output = "simple") {
    .Call('_visualizationQualityControl_ici_ref_kendallt', PACKAGE = 'visualizationQualityControl', x, y, perspective, output)
}

#' Calculates ici-kendall-tau matrix
#' 
#' @param x data matrix
#' @param perspective should we consider the "local" or "global" perspective?
#' 
#'
#' @name kendallt_matrix
#' @export
#' @useDynLib visualizationQualityControl
#' @return kendall tau correlation
ici_kendall_matrix <- function(x, perspective = "local") {
    .Call('_visualizationQualityControl_ici_kendall_matrix', PACKAGE = 'visualizationQualityControl', x, perspective)
}

