# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates it-kendall-tau
#' 
#' @param x numeric vector
#' @param y numeric vector
#' @param perspective should we consider the "local" or "global" perspective?
#' 
#' @examples 
#' data("grp_cor_data")
#' exp_data = grp_cor_data$data
#' x = exp_data[, 1]
#' y = exp_data[, 2]
#' kendallt(x, y)
#' cor(x, y, method = "kendall") 
#' 
#' x = sort(rnorm(100))
#' y = x + 1
#' y2 = y
#' y2[1:10] = NA
#' kendallt(x, y)
#' kendallt(x, y2, "global")
#' kendallt(x, y2)
#' 
#' @importFrom Rcpp sourceCpp
#' @name kendallt
#' @export
#' @useDynLib visualizationQualityControl
#' @return kendall tau correlation
kendallt <- function(x, y, perspective = "local") {
    .Call('_visualizationQualityControl_kendallt', PACKAGE = 'visualizationQualityControl', x, y, perspective)
}

