# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates it-kendall-tau
#' 
#' @param x numeric vector
#' @param y numeric vector
#' @param perspective should we consider the "local" or "global" perspective?
#' 
#' @importFrom Rcpp sourceCpp
#' @name kendallc
#' @export
#' @useDynLib visualizationQualityControl
#' @return kendall tau correlation
kendallc <- function(x, y, perspective = "local") {
    .Call('_visualizationQualityControl_kendallc', PACKAGE = 'visualizationQualityControl', x, y, perspective)
}

